name: my_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/calc.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/calc-adaptive.png"
  
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
